# Generated by Django 4.1.4 on 2022-12-24 01:56

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d65e462-58b0-467d-8fb7-dcd073a8cedb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
